---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-agent
  namespace: default
  labels:
    app: jaeger
    component: agent
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: zipkin-compact
    port: 5775
    targetPort: 5775
    protocol: UDP
  - name: compact
    port: 6831
    targetPort: 6831
    protocol: UDP
  - name: binary
    port: 6832
    targetPort: 6832
    protocol: UDP
  - name: configs
    port: 5778
    targetPort: 5778
    protocol: TCP
  - name: admin
    port: 14271
    targetPort: 14271
    protocol: TCP
  selector:
    app: jaeger
    component: agent
